// Package grid is the hub's view of its hosts: connected agents, jobs,
// enrollment. This file is the contract between the UI (views, httpserver) and
// the hosts. The real implementation (agent connections over mTLS) and the
// demo mode (simulated hosts) both implement Hub and Enroller; views and HTTP
// handlers must depend only on these interfaces and types.
//
// Conventions:
//   - IDs: HostID is the opaque 16-hex store.Host.ID. Job IDs are opaque
//     strings generated by the Hub implementation (also used as protocol.JobStart.JobID).
//   - Times are time.Time; implementations return UTC.
//   - Every method that changes something on a host takes an Actor and is
//     audited by the implementation (user, host, action, result). Callers must
//     not write a second audit entry for the same action.
//   - Validation of package and unit names happens in the Hub implementation
//     (and again on the agent); invalid values yield ErrInvalidArgument.
//   - Values returned (HostInfo, Snapshot, Job slices) are copies; callers may
//     keep and modify them.
package grid

import (
	"context"
	"errors"
	"io"
	"log/slog"
	"strconv"
	"time"

	"github.com/phabioo/nexara/internal/protocol"
)

// HostID identifies a host (store.Host.ID).
type HostID string

// Actor says who triggers an action, for the audit log.
type Actor struct {
	Operator string // operator ID; SystemActor.Operator for hub-initiated actions
	IP       string // remote IP of the browser; empty for system actions
}

// SystemActor is used for actions the hub starts on its own (auto-update of agents, ...).
var SystemActor = Actor{Operator: "system"}

// HostInfo is the list/detail view of one host.
type HostInfo struct {
	ID           HostID
	Name         string // unique short name, used in URLs
	DisplayName  string
	Address      string
	OS           string // "linux", "windows", "darwin"
	Arch         string // "arm64", "amd64"
	AgentVersion string
	Model        string // board/model from the agent's hello; empty if never connected since hub start
	Kernel       string // from hello, same caveat
	Online       bool
	LastSeen     time.Time // zero if never seen
	// Latency is the round-trip time of the last hub<->agent ping (shown in
	// the top bar, e.g. "4 MS"); 0 means unknown (offline or not measured yet).
	Latency      time.Duration
	Capabilities []string // enabled capability names (protocol.Cap*)
	// UpdateRequired is true when the agent is too old to be accepted and needs
	// the manual "Update required" action.
	UpdateRequired bool
	// RebootRequired mirrors the agent's /var/run/reboot-required flag.
	RebootRequired bool
}

// HasCapability reports whether the named capability is enabled on the host.
func (h HostInfo) HasCapability(name string) bool {
	for _, c := range h.Capabilities {
		if c == name {
			return true
		}
	}
	return false
}

// Snapshot is everything the UI needs to render a host's pages at one moment.
// Pointer fields are nil until the first data arrived (e.g. services are only
// fetched on demand).
type Snapshot struct {
	Host HostInfo
	// Metrics is the latest live sample; nil if none received yet or the host is offline since start.
	Metrics *protocol.Metrics
	// CPUHistory holds the last N total-CPU samples (percent, oldest first)
	// for the sparkline; N is chosen by the implementation (60 by default).
	CPUHistory []float64
	Services   *protocol.Services
	Packages   *protocol.Packages
	// Jobs are the running and queued jobs of the host, oldest first. Finished
	// jobs are available through Hub.Jobs.
	Jobs []Job
}

// JobState is the lifecycle state of a Job.
type JobState string

// Job states. queued -> running -> done | failed | canceled (queued can also go straight to canceled).
const (
	JobQueued   JobState = "queued"
	JobRunning  JobState = "running"
	JobDone     JobState = "done"
	JobFailed   JobState = "failed"
	JobCanceled JobState = "canceled"
)

// Finished reports whether the state is terminal.
func (s JobState) Finished() bool {
	return s == JobDone || s == JobFailed || s == JobCanceled
}

// JobLine is one retained output line of a job.
type JobLine struct {
	Stream protocol.JobStream
	Line   string
}

// JobSpec describes a job to start. Package is required for the pkg_* kinds
// and must be empty for the apt_* kinds.
type JobSpec struct {
	Kind    protocol.JobKind
	Package string
}

// Job is one entry of a host's job queue. Jobs run one at a time per host.
type Job struct {
	ID      string
	Host    HostID
	Kind    protocol.JobKind
	Package string
	State   JobState

	QueuedAt   time.Time
	StartedAt  time.Time // zero while queued
	FinishedAt time.Time // zero until finished

	// Output holds the retained output lines (the implementation keeps a
	// bounded number, dropping the oldest); the full stream is sent as job_output events.
	Output []JobLine

	OK             bool // meaningful once finished
	ExitCode       int
	Error          string
	RebootRequired bool

	RequestedBy string // Actor.Operator
}

// EventKind is the type of an Event.
type EventKind string

// Event kinds and their Payload types.
const (
	EventHostOnline  EventKind = "host_online"  // Payload: HostInfo
	EventHostOffline EventKind = "host_offline" // Payload: HostInfo
	EventHostAdded   EventKind = "host_added"   // Payload: HostInfo
	EventHostRemoved EventKind = "host_removed" // Payload: HostInfo (last known state)
	EventMetrics     EventKind = "metrics"      // Payload: protocol.Metrics
	EventServices    EventKind = "services"     // Payload: protocol.Services
	EventPackages    EventKind = "packages"     // Payload: protocol.Packages
	EventJobQueued   EventKind = "job_queued"   // Payload: Job
	EventJobStarted  EventKind = "job_started"  // Payload: Job (went from queued to running)
	EventJobOutput   EventKind = "job_output"   // Payload: JobOutputEvent
	EventJobDone     EventKind = "job_done"     // Payload: Job (finished: done, failed or canceled)
)

// Event is pushed to subscribers (the SSE endpoint of the UI).
type Event struct {
	Kind    EventKind
	Host    HostID
	Payload any // see the EventKind constants for the concrete type
}

// JobOutputEvent is the payload of EventJobOutput.
type JobOutputEvent struct {
	JobID string
	Line  JobLine
}

// ShellSession is an open Nexara Shell. Read returns terminal output, Write
// sends keyboard input, Close ends the session (and the remote shell). Read
// returns io.EOF once the remote shell has exited.
type ShellSession interface {
	io.ReadWriteCloser
	// Resize informs the remote PTY about the terminal size.
	Resize(cols, rows int) error
}

// Hub is what the UI uses to observe and control hosts.
type Hub interface {
	// Hosts lists all known hosts (online or not, revoked excluded), ordered by creation.
	Hosts() []HostInfo
	// Host returns one host; ok is false if unknown.
	Host(id HostID) (HostInfo, bool)
	// Snapshot returns the current state of a host; ok is false if unknown.
	Snapshot(id HostID) (Snapshot, bool)

	// Subscribe returns a channel of events for all hosts. The channel is
	// closed when ctx is cancelled. Delivery is best effort: a subscriber that
	// does not keep up may miss events, so treat events as change hints and
	// re-read via Snapshot after a reconnect.
	Subscribe(ctx context.Context) <-chan Event

	// RefreshServices asks the agent for its services and emits EventServices.
	// Errors: ErrHostNotFound, ErrHostOffline, ErrCapabilityDisabled.
	RefreshServices(ctx context.Context, id HostID) error
	// RefreshPackages asks the agent for its package list and emits EventPackages.
	// Errors: ErrHostNotFound, ErrHostOffline, ErrCapabilityDisabled.
	RefreshPackages(ctx context.Context, id HostID) error

	// SearchPackages asks the agent for packages matching query (for installing
	// packages that are not in the list yet). Not audited (read-only).
	// Errors: ErrHostNotFound, ErrHostOffline, ErrCapabilityDisabled, ErrInvalidArgument.
	SearchPackages(ctx context.Context, id HostID, query string) ([]protocol.Package, error)

	// RestartService restarts a service unit (audited).
	// Errors: ErrHostNotFound, ErrHostOffline, ErrCapabilityDisabled, ErrInvalidArgument.
	RestartService(ctx context.Context, actor Actor, id HostID, unit string) error

	// StartJob queues a job on the host and returns it in state queued (or
	// running if the queue was empty). Progress arrives as events.
	// Errors: ErrHostNotFound, ErrHostOffline, ErrCapabilityDisabled,
	// ErrInvalidArgument (bad kind/package), ErrJobBusy.
	StartJob(ctx context.Context, actor Actor, id HostID, spec JobSpec) (Job, error)
	// CancelJob cancels a queued or running job. Errors: ErrJobNotFound, ErrJobFinished.
	CancelJob(ctx context.Context, actor Actor, jobID string) error
	// Jobs returns the host's recent jobs (queued, running and recently
	// finished, bounded), newest first. Unknown host yields nil.
	Jobs(id HostID) []Job

	// UpdateAgent pushes the embedded agent binary to the host (the manual
	// "Update required" button; audited). The agent restarts and reconnects.
	// Errors: ErrHostNotFound, ErrHostOffline, ErrUnsupported (no embedded
	// binary for the host's os/arch).
	UpdateAgent(ctx context.Context, actor Actor, id HostID) error

	// RemoveHost retires a host (audited as host.remove): its agent
	// certificate is revoked, the live connection is closed and the host
	// disappears from Hosts. Works for online and offline hosts, including the
	// hub's own. EventHostRemoved is emitted.
	// Errors: ErrHostNotFound.
	RemoveHost(ctx context.Context, actor Actor, id HostID) error

	// OpenShell opens an interactive shell on the host (audited). The caller
	// owns the session and must Close it.
	// Errors: ErrHostNotFound, ErrHostOffline, ErrCapabilityDisabled.
	OpenShell(ctx context.Context, actor Actor, id HostID, cols, rows int) (ShellSession, error)
}

// Secret is a string that never shows up in logs, fmt output or JSON. Use
// Reveal to get the value at the single place that needs it.
type Secret string

// Reveal returns the secret value.
func (s Secret) Reveal() string { return string(s) }

// String implements fmt.Stringer and redacts the value.
func (s Secret) String() string { return s.redacted() }

// GoString redacts the value for %#v.
func (s Secret) GoString() string { return `grid.Secret("` + s.redacted() + `")` }

// LogValue redacts the value for log/slog.
func (s Secret) LogValue() slog.Value { return slog.StringValue(s.redacted()) }

// MarshalJSON redacts the value.
func (s Secret) MarshalJSON() ([]byte, error) { return []byte(`"` + s.redacted() + `"`), nil }

// MarshalText redacts the value (covers encoders other than encoding/json).
func (s Secret) MarshalText() ([]byte, error) { return []byte(s.redacted()), nil }

func (s Secret) redacted() string {
	if s == "" {
		return ""
	}
	return "[redacted]"
}

// SSHLinkRequest is the input of the "Via SSH" host enrollment. The SSH
// credentials are used only for the one-time agent installation: they must
// never be persisted, logged, put into audit details or echoed in progress
// messages, and are discarded when LinkViaSSH returns. The type redacts the
// password in String, GoString, LogValue and JSON.
type SSHLinkRequest struct {
	Address     string // host name or IP of the new host
	Port        int    // SSH port; 0 means 22
	User        string // SSH user, must have sudo rights
	DisplayName string // name shown in the UI; defaults to the detected hostname

	// Exactly one of Password and UseHubKey must be set.
	Password Secret
	// UseHubKey authenticates with the hub's own SSH key instead of a password.
	UseHubKey bool
}

// String implements fmt.Stringer without the password.
func (r SSHLinkRequest) String() string {
	port := r.Port
	if port == 0 {
		port = 22
	}
	auth := "hub-key"
	if !r.UseHubKey {
		auth = "password"
	}
	return "ssh " + r.User + "@" + r.Address + ":" + strconv.Itoa(port) + " [" + auth + "]"
}

// GoString keeps %#v from printing the password.
func (r SSHLinkRequest) GoString() string { return "grid.SSHLinkRequest{" + r.String() + "}" }

// LogValue implements slog.LogValuer without the password.
func (r SSHLinkRequest) LogValue() slog.Value {
	return slog.GroupValue(
		slog.String("address", r.Address),
		slog.Int("port", r.Port),
		slog.String("user", r.User),
		slog.Bool("hub_key", r.UseHubKey),
	)
}

// LinkStepName names one of the five steps shown in the Add-host dialog.
type LinkStepName string

// The five design steps, in order.
const (
	StepConnect LinkStepName = "connect" // open the SSH connection
	StepDetect  LinkStepName = "detect"  // detect OS and architecture
	StepInstall LinkStepName = "install" // copy binary and systemd unit
	StepEnroll  LinkStepName = "enroll"  // agent starts, pairs, receives its certificate
	StepOnline  LinkStepName = "online"  // agent connected and sending metrics
)

// LinkSteps lists the steps in display order.
func LinkSteps() []LinkStepName {
	return []LinkStepName{StepConnect, StepDetect, StepInstall, StepEnroll, StepOnline}
}

// LinkState is the state of a LinkStep.
type LinkState string

// Link step states.
const (
	LinkWaiting LinkState = "waiting"
	LinkRunning LinkState = "running"
	LinkDone    LinkState = "done"
	LinkFailed  LinkState = "failed"
)

// LinkStep is one progress update of LinkViaSSH. Detail is human readable
// ("Connected as pi", "Detected linux/arm64") and never contains credentials.
type LinkStep struct {
	Step   LinkStepName
	State  LinkState
	Detail string
}

// EnrollCode is a one-time code for manual enrollment.
type EnrollCode struct {
	Code    string    // shown once; the store keeps only its hash
	Expires time.Time // 15 minutes after creation
	// Command is the ready-to-paste one-liner for the new host, e.g.
	// curl -fsSL https://frpi5.local:8443/grid/install.sh | sudo sh -s -- <code>
	Command string
}

// Enroller adds hosts to the hub.
type Enroller interface {
	// LinkViaSSH installs the agent on the host over SSH and enrolls it.
	// progress is called from the calling goroutine for every state change
	// (may be nil). On success the host is online and its HostInfo returned.
	// The SSH credentials are discarded before returning, also on failure.
	// Errors: ErrLinkFailed (wraps the cause; the failing step was reported
	// through progress), ErrHostExists, ErrInvalidArgument.
	LinkViaSSH(ctx context.Context, actor Actor, req SSHLinkRequest, progress func(LinkStep)) (HostInfo, error)
	// NewEnrollCode creates a one-time enrollment code (valid 15 minutes).
	NewEnrollCode(ctx context.Context, actor Actor, opts EnrollOptions) (EnrollCode, error)
}

// EnrollOptions are the operator's choices for a new agent, applied when it enrolls.
type EnrollOptions struct {
	// Capabilities are the capability names (protocol.Cap*) to enable; nil
	// means the agent defaults.
	Capabilities []string
}

// Sentinel errors returned by Hub and Enroller implementations (use errors.Is).
var (
	ErrHostNotFound       = errors.New("grid: host not found")
	ErrHostOffline        = errors.New("grid: host is offline")
	ErrCapabilityDisabled = errors.New("grid: capability disabled on this host")
	ErrInvalidArgument    = errors.New("grid: invalid argument")
	ErrJobBusy            = errors.New("grid: an identical job is already queued or running")
	ErrJobNotFound        = errors.New("grid: job not found")
	ErrJobFinished        = errors.New("grid: job already finished")
	ErrHostExists         = errors.New("grid: host already exists")
	ErrLinkFailed         = errors.New("grid: linking the host failed")
	ErrUnsupported        = errors.New("grid: not supported on this host")
)
